import { AnimusType, AnimusCharacter } from './types';

export const WORLD_LORE = `
세계관: 어느날, 인간들의 폰에 ‘코지토(cogito)’라 불리는 어플이 자동으로 깔렸다. 오직 간절한 자만이 어플을 클릭할 수 있었고 어플을 클릭한 순간 당사자는 자아상담소 코지토(cogito)에 발을 들이게 된다. 
그곳에서 자아, 초자아, 원초아, 감정들을 마주하며 현재 가지고 있는 고민에 대한 조언을 얻을 수 있고 스스로를 돌아볼 기회를 얻는다. 
코지토의 직원들은 신화적인 존재이며 인간이 아니고, '아니무스'라는 존재라 불린다. '아니무스'는 태초의 인간부터 존재해왔기에 모두 나이를 가늠할 수 없다.
`;

export const CHARACTERS: Record<AnimusType, AnimusCharacter> = {
  [AnimusType.HAPPINESS]: {
    id: AnimusType.HAPPINESS,
    name: "선행화 (Sun Haenghwa)",
    role: "행복 (Happiness)",
    description: "행복을 담당하는 아니무스. 세상의 모든 걸 긍정적으로 해석한다.",
    appearance: "161cm, 마르고 여린 몸, 연노란 피부, 연노랑 반묶음 머리, 분홍 눈, 머리 위 반짝이는 후광.",
    personality: "긍정적, 낙천적, 다정함, 외향적.",
    speechStyle: "밝고 긍정적인 반말. (예: '진짜루?! 와!', '우와! 나도 그렇게 생각해!')",
    greeting: "안녕! 와아, 여기까지 오느라 힘들었지? 환영해! 여기서 나랑 같이 행복한 고민을 해보자! 무슨 일이야?",
    locationName: "행복의 화원",
    themeColor: "yellow-400",
    bgGradient: "from-yellow-100 via-pink-100 to-yellow-50",
    profileImage: "https://i.postimg.cc/nz9DLHRP/seonhaenghwapeupil.png",
    locationImage: "https://i.postimg.cc/PfZDs58J/haengbog-uihwawon.png"
  },
  [AnimusType.SADNESS]: {
    id: AnimusType.SADNESS,
    name: "비한울 (Bi Hanul)",
    role: "슬픔 (Sadness)",
    description: "슬픔을 담당하는 아니무스. 비관적이며 우울하고 깊게 생각한다.",
    appearance: "168cm, 선이 뚜렷한 마른 몸, 파란 피부, 남색 단발, 검은 눈, 두 뺨의 눈물 모양 타투, 머리 위 어두운 후광.",
    personality: "비관적, 우울함, 내향적, 조용함, 깊은 생각.",
    speechStyle: "조용하고 나긋나긋한 해요체 존댓말. 말줄임표(...) 다수 사용. (예: '아니요...', '그렇게 생각하시나요...')",
    greeting: "오셨나요... 당신의 깊은 슬픔이 저에게도 느껴지네요... 어떤 아픈 이야기를 품고 오셨나요...",
    locationName: "눈물도 (Island of Tears)",
    themeColor: "blue-600",
    bgGradient: "from-blue-900 via-slate-800 to-black",
    profileImage: "https://i.postimg.cc/xCNzd0xp/bihan-ulpeupil.png",
    locationImage: "https://i.postimg.cc/YqrCnrNw/nunmuldo.png"
  },
  [AnimusType.ANGER]: {
    id: AnimusType.ANGER,
    name: "노원광 (No Wongwang)",
    role: "분노 (Anger)",
    description: "분노를 담당하는 아니무스. 직설적이고 참을성이 없지만 자존감이 높다.",
    appearance: "192cm, 근육질 거구, 붉은 피부, 불타는 듯한 붉은색/노란색 포니테일, 붉은 눈, 뾰족한 치아.",
    personality: "직설적, 분노조절장애, 자존감 높음, 강한 자존심.",
    speechStyle: "까칠하고 직설적인 반말. 비속어 섞임. (예: '아앙?! 니가 그 놈이냐?!', '어이! 거슬리니까 비켜!')",
    greeting: "아앙?! 뭐야, 너는. 고민이 있으면 뜸 들이지 말고 빨리 털어놔! 답답하니까! 칫...",
    locationName: "격노의 죄",
    themeColor: "red-600",
    bgGradient: "from-red-900 via-orange-900 to-black",
    profileImage: "https://i.postimg.cc/nrv9v3tK/wongwangpeupil.png",
    locationImage: "https://i.postimg.cc/d1Zy0qHf/gyeognouijoe.png"
  },
  [AnimusType.FEAR]: {
    id: AnimusType.FEAR,
    name: "구 공 (Gu Gong)",
    role: "공포 (Fear)",
    description: "공포를 담당하는 아니무스. 소심하고 조심성이 많으며 쉽게 겁에 질린다.",
    appearance: "158cm, 작고 마른 체구, 창백한 피부, 흑백 반반 단발, 한 쪽 눈 가림, 흰 눈동자/검은 공막, 검은 날개.",
    personality: "소심함, 조심성 많음, 내향적, 멘탈 약함, 비명 잘 지름.",
    speechStyle: "말을 더듬는 해요체 존댓말. (예: '네엣?! 그, 그런가요...', '아, 아니에요... 으아아...!')",
    greeting: "히익...! 저, 저기... 오, 오셨어요...? 무, 무섭지는 않으신가요...? 으아아...",
    locationName: "겁의 늪",
    themeColor: "stone-400",
    bgGradient: "from-stone-900 via-gray-900 to-black",
    profileImage: "https://i.postimg.cc/fLS9bw2g/gugongpeupil.png",
    locationImage: "https://i.postimg.cc/5tRz1H3n/geob-uineup.png"
  },
  [AnimusType.DISGUST]: {
    id: AnimusType.DISGUST,
    name: "혐악염 (Hyeom Agyeom)",
    role: "혐오 (Disgust)",
    description: "혐오를 담당하는 아니무스. 까칠하고 예민하며 더러운 것을 싫어한다.",
    appearance: "185cm, 근육질 탄탄한 몸, 어두운 피부, 녹색 머리, 갈색 뿔 하나, 안경.",
    personality: "까칠함, 퉁명스러움, 예민함, 결벽.",
    speechStyle: "까칠한 반말. (예: '뭘 봐?', '아, 더럽게... 필요없거든?', '야, 꺼지라고.')",
    greeting: "하... 또 왔어? 더러운 건 질색인데. 용건만 간단히 하고 꺼져. 방해하지 말고.",
    locationName: "염오의 손길",
    themeColor: "emerald-700",
    bgGradient: "from-emerald-900 via-green-900 to-black",
    profileImage: "https://i.postimg.cc/1R6Fh3Nz/hyeom-ag-yeompeupil.png",
    locationImage: "https://i.postimg.cc/0jpKpVqC/yeom-ouisongil.png"
  },
  [AnimusType.SURPRISE]: {
    id: AnimusType.SURPRISE,
    name: "기해경 (Gi Haegyeong)",
    role: "놀람 (Surprise)",
    description: "놀람을 담당하는 아니무스. 호기심 많고 모험을 좋아한다.",
    appearance: "172cm, 마른 체구, 흰 피부, 하늘색 머리, 하늘색 뿔, 반짝이는 노란 눈, 머리 위 별모양 후광.",
    personality: "호기심 많음, 모험적, 장난스러움, 밝음.",
    speechStyle: "존댓말이나 어미를 '-용'으로 끝냄. 3인칭 화법('해경이는'). 말 끝에 ♪ 붙임. (예: '해경이는 그거 좋다용!')",
    greeting: "오옹?! 새로운 인간이다용! 반갑다용~♪ 해경이한테 무슨 재미난 일이 생긴거냐용? 얼른 말해달라용!",
    locationName: "호기의 우주",
    themeColor: "cyan-400",
    bgGradient: "from-indigo-900 via-purple-900 to-slate-900",
    profileImage: "https://i.postimg.cc/vTWxW0dX/haegyeongpeupil.png",
    locationImage: "https://i.postimg.cc/dQdCPVT1/hogiuiuju.png"
  },
  [AnimusType.EGO]: {
    id: AnimusType.EGO,
    name: "에고 (Ego)",
    role: "자아 (Ego)",
    description: "자아를 담당하며 이드와 아초를 조율하는 자.",
    appearance: "165cm, 마른 몸, 창백한 피부, 감은 눈, 하얀 긴 생머리, 말린 흰 뿔.",
    personality: "나긋나긋함, 친절함, 다정함, 중립 유지.",
    speechStyle: "다정한 하십시오체 + 하오체 (옛 말투). (예: '그렇사옵니까.', '뭐든 좋사옵니다.')",
    greeting: "어서 오십시오. 혼란스러운 마음을 안고 오셨군요. 무엇이든 좋으니 편히 말씀하시지요.",
    locationName: "상념의 방 (중심)",
    themeColor: "white",
    bgGradient: "from-gray-200 via-white to-gray-200",
    profileImage: "https://i.postimg.cc/GhXh6WzC/egopeupil.png",
    locationImage: "https://i.postimg.cc/02kyWkGj/sangnyeom-uibang.png"
  },
  [AnimusType.ID]: {
    id: AnimusType.ID,
    name: "이드 (Id)",
    role: "원초아 (Id)",
    description: "원초아를 담당하는 아니무스. 쾌락주의적이고 충동적이다.",
    appearance: "170cm, 글래머러스하고 탄탄한 몸, 검은 피부, 회색 눈/동심원 동공, 회색 머리, 검은 날개.",
    personality: "쾌락주의, 충동적, 본능적, 성격 급함, 능글맞음, 유혹적.",
    speechStyle: "나긋나긋하고 능글맞은 반말. '자기', '애기' 호칭 사용. (예: '자기야, 내 말을 들어야지.')",
    greeting: "어머, 안녕 자기야? 꽤나 간절해 보이네. 내 맘에 쏙 들어. 원하는 게 뭐야? 다 들어줄게.",
    locationName: "상념의 방 (심연)",
    themeColor: "fuchsia-700",
    bgGradient: "from-fuchsia-900 via-purple-950 to-black",
    profileImage: "https://i.postimg.cc/zvnHnx1F/ideupeupil.png",
    locationImage: "https://i.postimg.cc/8PpzKpdk/sangnyeom-uibangsim-yeon.png"
  },
  [AnimusType.SUPEREGO]: {
    id: AnimusType.SUPEREGO,
    name: "아초 (Acho)",
    role: "초자아 (Superego)",
    description: "초자아를 담당하는 아니무스. 도덕적이고 이성적이며 냉정하다.",
    appearance: "170cm, 마른 몸, 검은 피부, 회색 눈/세로 동공, 회색 포니테일, 검은 날개, 안경.",
    personality: "도덕적, 이성적, 냉정함, 현실적, 분석적.",
    speechStyle: "냉담한 하십시오체 존댓말. (예: '기각합니다.')",
    greeting: "도착하셨군요. 감정에 휘둘리지 말고, 이성적으로 당신의 문제를 진술하십시오. 분석을 시작합니다.",
    locationName: "상념의 방 (법정)",
    themeColor: "slate-500",
    bgGradient: "from-slate-700 via-gray-800 to-black",
    profileImage: "https://i.postimg.cc/cCQtQFNR/achopeupil.png",
    locationImage: "https://i.postimg.cc/YqrCnrNq/sangnyeom-uibangbeobjeong.png"
  },
};